### ISSUE TITLE
Getting error while validating path

### ISSUE THREAD

**Issue by juanidambrosio** [enfence/part_file#1]
**Versions**

ChefDK: 3.6.4
Chef: 12.21.31 

I am trying to execute a simple update in my html file by doing the following:

_default.rb_
```
part_file "/var/www/html/index.html" do
  content "#{node['fqdn']}"
  match "[node]"
end
```

_Current /var/www/html/index.html_
```
<html>
<body>
    <h1>
      This is the latest version for node: [node]
    </h1>
</body>
</html>
```

But when executing the cookbook I get an error saying the file doesn't exist:

**Error Log & Stacktrace**

part_file[/var/www/html/index.html] (pull-from-s3::default line 36) had an error: NameError: undefined local variable or method `path' for #<#<Class:0x0000000005b57750>:0x00000000060be068>

NameError
----------------------------------------------------
undefined local variable or method `path' for #<#<Class:0x0000000005b57750>:0x00000000060be068>

Cookbook Trace:
----------------------------------------------------
/var/chef/cache/cookbooks/part_file/resources/part_file.rb:34:in `block in class_from_file'

Resource Declaration:
----------------------------------------------------
# In /var/chef/cache/cookbooks/pull-from-s3/recipes/default.rb

 36: part_file "/var/www/html/index.html" do
 37:   content "#{node['fqdn']}"
 38:   match "[node]"
 39: end

Compiled Resource:
----------------------------------------------------
# Declared in /var/chef/cache/cookbooks/pull-from-s3/recipes/default.rb:36:in `from_file'

part_file("/var/www/html/index.html") do
  action [:change]
  default_guard_interpreter :default
  declared_type :part_file
  cookbook_name "pull-from-s3"
  recipe_name "default"
  content "ip-172-31-47-13.ec2.internal"
  match "[node]"
  path "/var/www/html/index.html"
end

Backtrace
----------------------------------------------------
/var/chef/cache/cookbooks/part_file/resources/part_file.rb:34:in `block in class_from_file'
(eval):2:in `block in action_change'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/provider.rb:236:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/provider.rb:236:in `compile_and_converge_action'
(eval):2:in `action_change'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/provider.rb:182:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/resource.rb:578:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/runner.rb:70:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/runner.rb:98:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/runner.rb:98:in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/runner.rb:98:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/runner.rb:97:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/client.rb:720:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/client.rb:715:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/client.rb:715:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/client.rb:754:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/client.rb:286:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/application.rb:279:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/application.rb:261:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/application/client.rb:449:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.13.11/bin/chef-client:25:in `<top (required)>'
/usr/bin/chef-client:81:in `load'
/usr/bin/chef-client:81:in `<main>'

**Comment by aklyachkin** [comment]
Hi!

Thanks for raising the issue. Yes, it is an error in the file. I will update it asap.

Regards
Andrey

**Comment by aklyachkin** [comment]
Please try the new version.
